server:
  port: 8060
#使用profile设置的dataId必须符合下面的规范
#dataId:{spring-application.name}-{profile.active}.{file-extension}
#配置文件是properties格式的拼接的时候可以不拼接格式，其他格式都需要在dataId中最后拼接文件格式
spring:
  profiles:
    active: dev
#配置文件的优先级（优先级大的会覆盖优先级小的，并且优先级大的中如果没有的配置项会自动从优先级小的中去获取）
#profile > 默认配置文件 > extension-configs(这是个列表，后被加载到的优先级大==下标越大，优先级越大) > shared-configs(这是个列表，后被加载到的优先级大==下标越大，优先级越大)
#不推荐使用profile的方式去配置不同环境的配置文件，因为这种方式无法进行权限控制
#权限控制是根据命名空间来进行配置的，故可以使用命名空间来区分不同环境的配置
